### ISSUE TITLE
apps not working and freezing emulator

### ISSUE THREAD

**Issue by mxmkmarquette** [Xposed-Modules-Repo/com.android1500.androidfaker#15]
i used version 1.8.3 but on both nosx and ldxplayer when updating the apps crash right aways if activated and on restart no able to used the vm anymore it just not boot.

**Comment by mmoadvert** [comment]
Same problem on memu and nox emulators. Please fix it.

**Comment by Android1500** [comment]
it fixed in v1.9.0
