### ISSUE TITLE
Device changer ask for vip but i bought already and activated

### ISSUE THREAD

**Issue by AnasusZXX** [Xposed-Modules-Repo/com.android1500.androidfaker#16]
I bought the activator and activated it. The app lets me change the sim operator and premium options but not device model

**Comment by AnasusZXX** [comment]
![Screenshot_2023-09-16-08-23-22-530-edit_com android1500 androidfaker](https://github.com/Xposed-Modules-Repo/com.android1500.androidfaker/assets/139763677/dc39f88c-0889-41db-b505-cf3434f1a426)

**Comment by Android1500** [comment]
only for vip users
