### ISSUE TITLE
app doesn't detect the granted permission [android 12/LSposed/Lineage19.0]

### ISSUE THREAD

**Issue by Axeltherabbit** [Xposed-Modules-Repo/com.android1500.androidfaker#3]
when I open it shows : "Module not active please activate it in Exposed or LSposed"
I enabled the module for "System Framework" on LSposed and rebooted already.

**Comment by Android1500** [comment]
> when I open it shows : "Module not active please activate it in Exposed or LSposed"
> 
> I enabled the module for "System Framework" on LSposed and rebooted already.

Fixed in latest version v1.8.1
