### ISSUE TITLE
WARNING!

### ISSUE THREAD

**Issue by ultrahacker678** [Xposed-Modules-Repo/com.android1500.androidfaker#5]
AFTER ACTIVATING THIS MODULE IN LSPOSED/XPOSED YOUR PHONE MAY GET BOOT LOOP! I MIRACULOUSLY got out of it (after ~ 30 reboots I was able to reboot the phone with flight mode, since it was the network connection that caused the reboot, I was able to go to the application list and delete this program)!  Phone: Samsung galaxy m52.

**Comment by Android1500** [comment]
this issue already fixed in new version
