### ISSUE TITLE
Asks to hide apps

### ISSUE THREAD

**Issue by yassineomarii** [Xposed-Modules-Repo/com.android1500.androidfaker#7]
Hello everyone 🙂

A message pops up when I press fast reboot asks to hide apps such as (Youtube, "android.overlay.reduce...", )

But it keeps asking for the same app untill I uninstall it, I even uninstalled system apps (I'm noob at this). Apps that I don't even know what their job is :v

Android 12
Phone: Xiaomi Mi 8 (dipper)
ROM: Evolution x (ver 6.4)

Please help :)

![Screenshot_20220625-123634_Android Faker](https://user-images.githubusercontent.com/105060396/175772078-c45f5b98-7cf5-4217-b43c-8f38489a223d.png)

**Comment by araafroyall** [comment]
there is no need to reboot to provide fake values to apps. just ignore selecting system framework
